---
apiVersion: v1
kind: Pod
metadata:
  name: backend-app
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: backend-app
  containers:
    - name: backend-app
      image: "mcr.microsoft.com/azure-cli:latest"
      args:
        - '/bin/bash'
        - '-c'
        - 'sleep infinity'