apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # This annotation is optional - it should be used when there are  
    # one-to-many relationships with the kubernetes service account 
    # and Azure identities. More details in the documentation: 
    # https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#service-account-labels-and-annotations
    #
    # azure.workload.identity/client-id: "${USER_ASSIGNED_CLIENT_ID}"
  name: backend-app
  namespace: default